[17 장성준] ReviewView 완성
wecode-bootcamp-korea/17-1st-200store-backend pull request #10
Opened 2021-02-20 17:53 UTC by ique-coder

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ReviewView 완성(httpie 통신 O, front와 통신 X)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- GET을 했을시, 해당 product_id값을 조회하여 뿌려줌
- POST 했을 시, MathcingReview 테이블에 값이 있으면 create해줌
  - create시 트랜잭션 처리하여 Review테이블에 값도 넣어 create 해줌
- product의 models.py중 
  - ReviewStatus -> MatchingReview로 수정, product 컬럼 추가, review 참조관계 변경(product->review)
  - ProductInquiry -> db_table 이름 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 02:00 UTC, Kang-kyunghun requested changes

2021-02-22 02:00 UTC, Kang-kyunghun commented on product/views.py
> +                )
transaction을 사용한 이유가 있을까요?

2021-02-23 02:22 UTC, Kang-kyunghun requested changes

2021-02-23 02:22 UTC, Kang-kyunghun commented on product/views.py
> +
transaction에서 에러가 발생 했을 때 에러 처리도 해주세요.
그리고, transaction이 완료 되었을 때 commit 또는 rollback의 작업이 이루어져야 하는데, 이 부분도 확인해 주세요.

2021-02-23 04:17 UTC, ique-coder commented on product/views.py
> +
네 알겠습니다!

2021-02-23 09:26 UTC, ique-coder commented on product/views.py
> +
<img width="343" alt="스크린샷 2021-02-23 오후 6 26 23" src="https://user-images.githubusercontent.com/51706303/108824099-aaa7c300-7604-11eb-819d-1d29dc38167b.png">

2021-02-23 12:10 UTC, Kang-kyunghun commented
transaction 구현 하느라 고생 하셨습니다.!!1
7시간 고민의 결과~

2021-02-23 12:10 UTC, merged