[17기 정희영] 장바구니 기능구현
wecode-bootcamp-korea/17-1st-200store-backend pull request #13
Opened 2021-02-23 16:21 UTC by sayxyoung

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 기능구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 담기 구현
- 장바구니에 담긴 제품 삭제 기능 구현
- 현재 담긴 장바구니 보기 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-23 17:26 UTC, Kang-kyunghun requested changes

2021-02-23 17:26 UTC, Kang-kyunghun commented on order/views.py
> +class CartView(View):
한 칸 띄어 주세요
```suggestion
SHOPPING_BASKET = "장바구니"

class CartView(View):
```

2021-02-24 01:39 UTC, sayxyoung commented on order/views.py
> +class CartView(View):
넵 알겠습니다

2021-02-24 05:23 UTC, Kang-kyunghun requested changes

2021-02-24 05:23 UTC, Kang-kyunghun commented on order/views.py
> +            cart_lists   = Cart.objects.filter(order=order)
Order 테이블에 order_status와 cart가 연결 되어 있을 것으로 보입니다.
order 하나만 가지고, cart까지 연관 지어서 가져 올 수 있습니다.
한 번 고민해 보시고 수정 부탁드립니다.

2021-02-24 05:23 UTC, Kang-kyunghun commented on order/views.py
> +            delete_productId_list = [product_list[idx]['productId'] for idx in range(len(product_list))]
cart에 담긴 상품을 지우기 위해서 프론트에서 cart_id를 받아올 수 있으면 cart_id만으로도 delete 로직을 쉽게 짤 수 있습니다. 
프론트에서 cart_id를 받을려면 cart를 post 할 때 프론트에게 cart_id를 주면 되겠죠?

2021-02-24 05:23 UTC, Kang-kyunghun commented on order/views.py
> +
post method는 전체적으로 저랑 한 번 보겠습니다.
아래 다른 부분들부터 수정 해주세요.

2021-02-24 09:18 UTC, sayxyoung commented on order/views.py
> +            cart_lists   = Cart.objects.filter(order=order)
아래와 같이 역참조 이용해서 원하는 값을 호출도록 변경하였습니다.
cart_list = order.cart_set.all()

2021-02-24 09:20 UTC, sayxyoung commented on order/views.py
> +            delete_productId_list = [product_list[idx]['productId'] for idx in range(len(product_list))]
get요청시, cart_id 값을 전달하도록 변경하였고,
delete요청시, cart_id를 query method로 전달받아 삭제 되도록 변경하였습니다.

2021-02-24 09:20 UTC, sayxyoung commented on order/views.py
> +
네 알겠습니다.

2021-02-24 10:56 UTC, Kang-kyunghun requested changes

2021-02-24 10:56 UTC, Kang-kyunghun commented on order/views.py
> +            order_status = OrderStatus.objects.get(name=SHOPPING_BASKET)
따로 객체를 만들지말고, 상태값을 filte에 적요해 보세요.

2021-02-24 10:56 UTC, Kang-kyunghun commented on order/views.py
> +                )
```suggestion
               order = Order.objects.create(
                    user          = user,
                    status        = order_status,
                    address       = address[0],
                    total_price   = 0,
                    serial_number = '추가구현예정',
                    
                    Cart.objects.create() 
                    return 
                )
```

2021-02-24 10:56 UTC, Kang-kyunghun commented on order/views.py
> +            totalPrice = data['totalPrice']
python 변수 컨벤션에 맞춰 주세요.

2021-02-24 11:04 UTC, sayxyoung commented on order/views.py
> +            totalPrice = data['totalPrice']
네 알겠습니다.

2021-02-24 11:29 UTC, sayxyoung commented on order/views.py
> +                )
주문리스트 없을 시,
주문 생성 후 즉시 장바구니도 생성되게 수정하였습니다.

2021-02-24 11:43 UTC, Kang-kyunghun requested changes

2021-02-24 11:43 UTC, Kang-kyunghun commented on order/views.py
> +            order       = Order.objects.get(user=user, status__name=SHOPPING_BASKET)
order가 사용되는 곳이 없습니다. 필요 없다면 제거해 주세요.

2021-02-24 11:48 UTC, sayxyoung commented on order/views.py
> +            order       = Order.objects.get(user=user, status__name=SHOPPING_BASKET)
불필요한 객체(order, user) 삭제 하였습니다.

2021-02-25 02:41 UTC, Kang-kyunghun requested changes

2021-02-25 02:41 UTC, Kang-kyunghun commented on order/views.py
> +            order        = Order.objects.get(user=user, status__name=SHOPPING_BASKET)
만약에 .get으로 불러오는 데이터가 2개 이상이면 어떤 에러가 발생 할까요? 어떤 에러가 나는지 알아보고 예외 처리 해주세요.

2021-02-25 02:46 UTC, Kang-kyunghun requested changes

2021-02-25 02:46 UTC, Kang-kyunghun commented on order/views.py
> +                    serial_number = str(user.id)+uuid_number,
user_id 빼주시고, uuid로만 해주세요.

2021-02-25 03:09 UTC, sayxyoung commented on order/views.py
> +            order        = Order.objects.get(user=user, status__name=SHOPPING_BASKET)
get에서 2개 이상일 경우 예외처리는 생각을 안해봤었는데 !
감사합니다. 확인하고 예외처리 해보겠습니다.

2021-02-25 03:12 UTC, sayxyoung commented on order/views.py
> +                    serial_number = str(user.id)+uuid_number,
네 알겠습니다 !
uuid4 length print로 찍어봤는데 
말씀하신대로 36이였습니다 //

2021-02-25 07:05 UTC, Kang-kyunghun requested changes

2021-02-25 07:05 UTC, Kang-kyunghun commented on order/views.py
> +                    total_price   = 0,
defalut 값과 같으면 제거해 주셔도 됩니다.

2021-02-25 07:05 UTC, Kang-kyunghun commented on order/views.py
> +                    'eachPrice' : int(cart_list.total_price/cart_list.quantity),
나누지 말고 db에 있는 값을 가져와 주세요.

2021-02-25 07:09 UTC, sayxyoung commented on order/views.py
> +                    total_price   = 0,
불필요한 코드 삭제하도록 하겠습니다.

2021-02-25 07:09 UTC, sayxyoung commented on order/views.py
> +                    'eachPrice' : int(cart_list.total_price/cart_list.quantity),
참조하여 db에서 price 정보 가져오도록 수정하겠습니다.

2021-02-25 07:15 UTC, merged

2021-02-25 07:15 UTC, Kang-kyunghun commented
정말 고생 많으셨습니다.~~!!