[17기 장성준] MainView 완성
wecode-bootcamp-korea/17-1st-200store-backend pull request #7
Opened 2021-02-19 11:41 UTC by ique-coder

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- MainView 작성 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- MainView 완료
- models 수정으로 데이터 http 연결 확인은 못해봄...
- main page에 best 4개, new 8개, sale 8개를 나타내는 로직 완성
- list comprehension 적용
- 함수를 써서 프론트에서 sale, best, new 딱지 붙여주는 is_OO 키 값 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 01:44 UTC, Kang-kyunghun requested changes

2021-02-22 01:44 UTC, Kang-kyunghun commented on product/views.py
> +utc.localize(datetime.utcnow())
이 부분에 대해서 이야기가 필요할 것 같습니다.

2021-02-22 01:44 UTC, Kang-kyunghun commented on product/views.py
> +    return True if sale > 0 else False
파이썬에서 함수명은 스네이크 케이스를 사용합니다. 수정해 주세요.

2021-02-22 01:44 UTC, Kang-kyunghun commented on product/views.py
> +        best_query = Product.objects.all().only('id', 'name', 'image_url', 'category', 'price', 'sale','create_at').order_by('-total_sales')[:4]
1. [:4] 부분 hard coding 수정해 주세요.
2. only를 사용한 이유를 적어 주세요.

2021-02-22 01:44 UTC, Kang-kyunghun commented on product/views.py
> +        new_query  = Product.objects.all().only('id', 'name', 'image_url', 'category', 'price', 'sale','create_at').order_by('-sale')[:8]
[:8] 부분 hard coding 수정해 주세요.

2021-02-22 01:44 UTC, Kang-kyunghun commented on product/views.py
> +        sale_query = Product.objects.filter(sale__gt=0).only('id', 'name', 'image_url', 'category', 'price', 'sale','create_at')[:8]
[:8] 부분 hard coding 수정해 주세요.

2021-02-22 01:44 UTC, Kang-kyunghun commented on store200/urls.py
> +        path('main', include('product.urls')),
이미 product가 product.urls을 include하고 있는데 main을 추가한 이유가 궁금합니다.

2021-02-22 04:03 UTC, ique-coder commented on product/views.py
> +utc.localize(datetime.utcnow())
삭제했습니다!

2021-02-22 04:04 UTC, ique-coder commented on product/views.py
> +    return True if sale > 0 else False
넵! 감사합니다!

2021-02-22 04:05 UTC, ique-coder commented on product/views.py
> +        best_query = Product.objects.all().only('id', 'name', 'image_url', 'category', 'price', 'sale','create_at').order_by('-total_sales')[:4]
모든 부분을 가져오는것보다 only로 가져오는 것이 속도면에서 더 빠르지 않을까? 해서 사용했습니다!

2021-02-22 04:05 UTC, ique-coder commented on product/views.py
> +        new_query  = Product.objects.all().only('id', 'name', 'image_url', 'category', 'price', 'sale','create_at').order_by('-sale')[:8]
넵!

2021-02-22 04:05 UTC, ique-coder commented on product/views.py
> +        sale_query = Product.objects.filter(sale__gt=0).only('id', 'name', 'image_url', 'category', 'price', 'sale','create_at')[:8]
넵!

2021-02-22 04:07 UTC, ique-coder commented on store200/urls.py
> +        path('main', include('product.urls')),
main 페이지라서 /main으로 왔을때 이동하게 하려고 그렇게 했습니다.
기존에 있던 /product로 하게 되면 url 주소가 /product/main으로 이동해서요...!

2021-02-23 12:41 UTC, Kang-kyunghun commented on product/views.py
> +from .models      import Product # image_url 추가하면 구성해주기
불필요한 주석은 제거해  주세요.

2021-02-23 17:40 UTC, merged