[17기 송빈호] Product views.py 작성 완료
wecode-bootcamp-korea/17-1st-200store-backend pull request #8
Opened 2021-02-20 04:15 UTC by binogood

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- product views.py 작성 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 전체 및 카테고리에 따라 전체면 물건 전체를 보내주고 카테고리 id를 받으면 그 카테고리에 해당하는 물품을 보내주는 views.py 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 3항 연산자를 사용해서 전체 뿌려주는 것과 카테고리별로 뿌려주는것을 구분 했는데 너무 깁니다.. 줄이는 방법이 있을까요 ?
- filter를 구현을 하려고 하는데 elif를 될수 있으면 쓰지 말라고 들었던거 같아서 혹시 다른 방법이 있을까요 ?
- Q 객체를 이용하여 작성해보려고 했지만 ... 이게 조건 마다 실행되는것들이 다 달라서 어떻게 해야될지 모르겠습니다..

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 01:59 UTC, Kang-kyunghun requested changes

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +    return True if create_at > compare_date else False
파이썬에서 함수명은 스네이크 케이스를 사용합니다.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +        category_id).order_by(sorting)
return 뒤에 코드들은 실행이 안 될 것 같은데 로직 한 번 더 확이해 주세요.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +    return True if sale > 0 else False
파이썬에서 함수명은 스네이크 케이스를 사용합니다.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +            sorting = '-total_sales'
sorting을 위한 query parameter을 받기 위해 kwargs을 사용한 것으로 보입니다. 
kwargs을 사용하지 않고, query parameter을 받을 수 있는 방법이 있습니다. 한 번 찾아보시고 수정 해주세요.
그리고 프론트에서 sorting하는 기준을 바로 받으면 조건문을 안 써도 될 것 같은데 이 부분도 팀원들과 상의해 보세요.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +        print(products)
불피요한 print는 제거해 주세요.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +
wecode 컨벤션에서는 class 사이의 간격은 한 칸입니다.
자동으로 라인 맞춰주는 플러그인 사용하여 2칸으로 바꿔줄 것으로 예상 됩니다.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +#
불필요한 주석은 제거해 주세요.

2021-02-22 01:59 UTC, Kang-kyunghun commented on product/views.py
> +            } for image in images]
product_view list에 image에 대한 정보가 있어, product_images list로 다시 이미지에 대한 정보를 받을 필요는 없어 보입니다.
이미지에 id가 같이 필요한 것이라면 produt_view list에 같이 담아 주세요.

2021-02-22 02:03 UTC, binogood commented on product/views.py
> +        category_id).order_by(sorting)
수정하겠습니다 !

2021-02-22 02:03 UTC, binogood commented on product/views.py
> +    return True if create_at > compare_date else False
넵 수정하겠습니다!

2021-02-22 02:06 UTC, binogood commented on product/views.py
> +            } for image in images]
product_view에 있는 이미지는 전체리스트에 필요한 메인사진의 image입니다.

2021-02-22 02:07 UTC, binogood commented on product/views.py
> +#
제거하도록 하겠습니다!

2021-02-22 02:08 UTC, binogood commented on product/views.py
> +
수정하겠습니다 !

2021-02-22 02:10 UTC, binogood commented on product/views.py
> +            sorting = '-total_sales'
프론트랑 얘기해서 수정하도록 하겠습니다.

2021-02-22 12:05 UTC, Kang-kyunghun requested changes

2021-02-22 12:05 UTC, Kang-kyunghun commented on product/views.py
> +
category_id를 query parameter로 받아오는 로직 구현 해주세요.

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +            }]
제품 정보는 하나밖에 없어서 리스트에 들어가있지 않아도 될 것 같은데, list로 선언하신 이유가 있나요?

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +
깔끔한 코드를 위해서 불필요한 공백은 제거해주세요

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +            return JsonResponse({'message' : 'DOSE_NOT_EXISTS_PRODUCT'}, status=401)
```suggestion
            return JsonResponse({'message' : 'PRODUCT_DOSE_NOT_EXIST'}, status=404)
```
데이터가 없을 때에, `404`에러를 많이 활용합니닷

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +
```suggestion

        return JsonResponse({'data' : products}, status=200)

```
데이터가 담겨가면, message는 따로 전달하지 않으셔도 될 것 같습니다 👍

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +                    'imageUrl'       : product.image_url,
```suggestion
                    'id'       : product.id,
                    'name'     : product.name,
                    'price'    : product.price,
                    'sale'     : product.sale,
                    'stock'    : product.stock,
                    'imageUrl' : product.image_url,
```
간격 너무 넓지 않아도 됩니다

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +            } for image in images]
@Kang-kyunghun 경훈님 ㅎㅎ 빈호님 list comprehension 전부 딕셔너리에 넣어보시기로 하셨습니다 ㅎㅎ 화이팅을 외쳐줍시다!

2021-02-23 11:15 UTC, soheon-lee commented on product/views.py
> +
```suggestion

def is_new(create_at, compare_date):
    return create_at > compare_date

def check_best_list():
    best_query = Product.objects.all().order_by('total_sales')[:10]
    return [best.id for best in best_query]

def is_best(check_list, id):
    return id in checkList

def is_sale(sale):
    return sale > 0

```
파이썬에서는 if 조건문 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)

이것이 보다 '파이썬다운' 코드라고 할 수 있습니다

2021-02-23 11:17 UTC, binogood commented on product/views.py
> +            }]
보니깐 필요없는것 같습니다 지우도록 하겠습니다 !

2021-02-23 11:18 UTC, binogood commented on product/views.py
> +
공백 .. 바로 제거하도록 하겠습니다 !

2021-02-23 11:18 UTC, soheon-lee commented
@binogood 빈호님 커밋 메세지는 어떤 파일을 수정했는지를 기록하는 것이 아닙니다. :) 어떤 파일 수정했는지는 git이 자동으로 기록합니다.
대신, 우리는 커밋메세지에 '내가 어떤 작업을 했는지' 기록하셔야 합니다. 내부 파일에서 어떤 기능을 수정하고, 리팩토링 했는지를 기록해주세요.

단순히 "내가 어떤 파일을 수정했다"라고 한다면, 수많은 커밋 메세지들이 똑같이 메세지를 전달하게 되고, 이는 커밋 메세지가 제대로 자신의 역할을 하고 있다고 할 수 없습니다. :) 다음부터는 보다 정확한 수정 내역을 기록해서 커밋해주세요~~

커밋 컨벤션은 너무 너무 잘 지켜주셨습니다. 매우 깔끔합니다 👍 👍 👍 👍

2021-02-23 11:18 UTC, binogood commented on product/views.py
> +            return JsonResponse({'message' : 'DOSE_NOT_EXISTS_PRODUCT'}, status=401)
오 .. 좋은 정보 감사합니다 404 자주 애용하도록 하겠습니다 !

2021-02-23 11:20 UTC, binogood commented on product/views.py
> +
프론트의 기쁨을 위해 전달하는 메세지였는데... 이제 프론트는 웁니다 ..

2021-02-23 11:21 UTC, binogood commented on product/views.py
> +                    'imageUrl'       : product.image_url,
넵 !! 주의하도록 하겠습니다 !

2021-02-23 11:44 UTC, soheon-lee commented on product/views.py
> +
`review`도 같이 합쳐보세요 👍

2021-02-23 17:34 UTC, Kang-kyunghun requested changes

2021-02-23 17:34 UTC, Kang-kyunghun commented on product/views.py
> +
불필요한 공백 제거해 주세요.

2021-02-23 17:34 UTC, Kang-kyunghun commented on product/views.py
> +                    'imageUrl'  : product.image_url,
thumbnailUrl로 키 값을 바꾸는 어떨까요? 아래 imageUrls랑 혼동도 피하고 의미 전달도 더 명확할 것 같습니다.(의견)

2021-02-23 17:34 UTC, Kang-kyunghun commented on product/views.py
> +        }
```suggestion
                    'reviews'   : [{
                                    'id'         : review.id,
                                    'reviewTitle': review.title,
                                    'content'    : review.content,
                                    'starRating' : review.star_rating,
                                    'createAt'   : review.create_at,
                                    'userId'     : review.user_id
                                   } for review in reviews]
        }
```

2021-02-23 18:23 UTC, binogood commented on product/views.py
> +
맨 마지막에 한칸 공백둬야 되는걸로 알고 있습니다... 안하면 에러발생하던데 지워도 되는건가요 ?

2021-02-23 18:24 UTC, binogood commented on product/views.py
> +                    'imageUrl'  : product.image_url,
오 의견 감사합니다! 참고해서 수정하도록 하겠습니다.

2021-02-23 18:25 UTC, binogood commented on product/views.py
> +        }
위와 같이 수정하도록 하겠습니다!

2021-02-24 01:40 UTC, soheon-lee commented on product/views.py
> +        }
오.. 대박! good good! 이제 JSON의 세상을 마음대로 넘나드는 사람이 되셨네요 축하축하추~ 🥳  머리 아프셨을텐데 고생하셨습니다 ㅎㅎ

2021-02-24 01:41 UTC, soheon-lee commented
Conflict만 수정하시면, 경훈님 의견에 따라 merge 해주실 것 같네요 👍 
conversation 36개.. 고생하셨습니다...

2021-02-24 01:57 UTC, binogood commented on product/views.py
> +        }
하핳.. 감사합니다 !!

2021-02-24 02:00 UTC, binogood commented
성준님 merge하면 그때 수정해서 올리도록 하겠습니다 .. 또 컴플릭트 뜰거 같아서..

2021-02-24 04:48 UTC, Kang-kyunghun commented
LGTM 굿~~

2021-02-24 04:48 UTC, merged